from __future__ import annotations

import re
from pathlib import Path
from typing import Any

import yaml

from ai_strategy_brain.strategy_spec_validator import load_strategy_spec, validate_strategy_spec
from core.config_loader import load_global_config
from core.database import execute, insert_dict, utc_now
from core.paths import SRC_DIR, resolve_project_path
from core.validation import validate_generated_code_safety


def class_name(strategy_name: str) -> str:
    parts = re.split(r"[^A-Za-z0-9]+", strategy_name)
    return "".join(part.capitalize() for part in parts if part) + "Strategy"


def _value_expression(value: Any) -> str:
    if isinstance(value, (int, float)):
        return str(value)
    return f"dataframe['{value}']"


def _condition_expression(condition: dict[str, Any]) -> str:
    left = f"dataframe['{condition['indicator']}']"
    right = _value_expression(condition["value"])
    return f"({left} {condition['operator']} {right})"


def _logic_expression(block: dict[str, Any]) -> str:
    key = "all" if "all" in block else "any"
    joiner = " & " if key == "all" else " | "
    return joiner.join(_condition_expression(condition) for condition in block[key])


def render_freqtrade_strategy(spec: dict[str, Any]) -> str:
    cls = class_name(spec["strategy_name"])
    entry_expression = _logic_expression(spec["entry_logic"])
    exit_expression = _logic_expression(spec["exit_logic"])
    spec_yaml = yaml.safe_dump(spec, sort_keys=False).replace('"""', '\\"\\"\\"')
    stoploss = float(spec["risk"].get("stop_loss", -0.03))
    trailing = bool(spec["risk"].get("trailing_stop", True))
    take_profit = abs(float(spec["risk"].get("take_profit", 0.06)))
    minimal_roi = {"0": take_profit}
    return f'''# Generated by Trading Research OS from YAML spec: {spec["strategy_name"]}
# Spot-only research strategy. Leverage and futures are disabled by design.
from __future__ import annotations

from functools import reduce

import pandas as pd
from pandas import DataFrame
from freqtrade.strategy import IStrategy


class {cls}(IStrategy):
    """
    Source YAML spec:
{_indent(spec_yaml, 4)}
    """

    timeframe = "{spec["timeframe"]}"
    can_short = False
    stoploss = {stoploss}
    trailing_stop = {trailing}
    minimal_roi = {minimal_roi!r}
    process_only_new_candles = True
    startup_candle_count = 240
    max_open_trades = {int(spec["risk"].get("max_open_trades", 3))}

    def leverage(self, *args, **kwargs) -> float:
        return 1.0

    @staticmethod
    def _rsi(series: pd.Series, window: int = 14) -> pd.Series:
        delta = series.diff()
        gain = delta.clip(lower=0).rolling(window).mean()
        loss = (-delta.clip(upper=0)).rolling(window).mean()
        rs = gain / loss.replace(0, np.nan)
        return 100 - (100 / (1 + rs))

    @staticmethod
    def _atr(dataframe: DataFrame, window: int = 14) -> pd.Series:
        previous_close = dataframe["close"].shift(1)
        true_range = pd.concat(
            [
                dataframe["high"] - dataframe["low"],
                (dataframe["high"] - previous_close).abs(),
                (dataframe["low"] - previous_close).abs(),
            ],
            axis=1,
        ).max(axis=1)
        return true_range.rolling(window).mean()

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe["ema_20"] = dataframe["close"].ewm(span=20, adjust=False).mean()
        dataframe["ema_50"] = dataframe["close"].ewm(span=50, adjust=False).mean()
        dataframe["ema_200"] = dataframe["close"].ewm(span=200, adjust=False).mean()
        dataframe["sma_20"] = dataframe["close"].rolling(20).mean()
        dataframe["rsi_14"] = self._rsi(dataframe["close"], 14)
        dataframe["atr_14"] = self._atr(dataframe, 14)
        dataframe["bb_middle"] = dataframe["close"].rolling(20).mean()
        bb_std = dataframe["close"].rolling(20).std()
        dataframe["bb_upper"] = dataframe["bb_middle"] + 2 * bb_std
        dataframe["bb_lower"] = dataframe["bb_middle"] - 2 * bb_std
        fast = dataframe["close"].ewm(span=12, adjust=False).mean()
        slow = dataframe["close"].ewm(span=26, adjust=False).mean()
        dataframe["macd"] = fast - slow
        dataframe["macd_signal"] = dataframe["macd"].ewm(span=9, adjust=False).mean()
        dataframe["macd_hist"] = dataframe["macd"] - dataframe["macd_signal"]
        dataframe["rolling_return_24"] = dataframe["close"].pct_change(24)
        dataframe["rolling_volatility_24"] = dataframe["close"].pct_change().rolling(24).std()
        dataframe["volume_sma_20"] = dataframe["volume"].rolling(20).mean()
        volume_std = dataframe["volume"].rolling(20).std().replace(0, np.nan)
        dataframe["volume_zscore"] = (dataframe["volume"] - dataframe["volume_sma_20"]) / volume_std
        dataframe["drawdown"] = dataframe["close"] / dataframe["close"].cummax() - 1
        dataframe["liquidity_proxy"] = dataframe["close"] * dataframe["volume"]
        dataframe["spread_proxy"] = (dataframe["high"] - dataframe["low"]) / dataframe["close"]
        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        conditions = [{entry_expression}]
        if conditions:
            dataframe.loc[reduce(lambda left, right: left & right, conditions), "enter_long"] = 1
        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        conditions = [{exit_expression}]
        if conditions:
            dataframe.loc[reduce(lambda left, right: left & right, conditions), "exit_long"] = 1
        return dataframe
'''


def _indent(text: str, spaces: int) -> str:
    prefix = " " * spaces
    return "\n".join(prefix + line for line in text.splitlines())


def convert_spec_file(path: str | Path) -> Path:
    spec = load_strategy_spec(path)
    valid, errors = validate_strategy_spec(spec)
    if not valid:
        raise ValueError("; ".join(errors))
    if spec["engine_target"] != "freqtrade":
        raise ValueError(f"Spec target is {spec['engine_target']}, not freqtrade.")
    runtime_paths = load_global_config().get("runtime_paths", {})
    output_dir = resolve_project_path(
        runtime_paths.get("generated_freqtrade_strategies", "data/generated/freqtrade_strategies")
    )
    output_dir.mkdir(parents=True, exist_ok=True)
    code_path = output_dir / f"{class_name(spec['strategy_name'])}.py"
    code = render_freqtrade_strategy(spec)
    safe, safety_errors = validate_generated_code_safety(code)
    if not safe:
        raise ValueError(f"Generated strategy safety validation failed: {safety_errors}")
    code_path.write_text(code, encoding="utf-8")
    execute(
        "DELETE FROM generated_strategies WHERE strategy_id = ? AND engine_target = ?",
        (spec["strategy_name"], "freqtrade"),
    )
    insert_dict(
        "generated_strategies",
        {
            "generated_id": f"gen_{spec['strategy_name']}_freqtrade",
            "strategy_id": spec["strategy_name"],
            "engine_target": "freqtrade",
            "code_path": str(code_path),
            "template_version": "freqtrade_spot_v1",
            "created_at": utc_now(),
        },
    )
    return code_path


def convert_all_specs(spec_dir: str | Path | None = None) -> list[Path]:
    if spec_dir:
        directory = Path(spec_dir)
    else:
        runtime_paths = load_global_config().get("runtime_paths", {})
        directory = resolve_project_path(runtime_paths.get("generated_specs", "data/generated/specs"))
        if not directory.exists():
            directory = SRC_DIR / "ai_strategy_brain" / "generated_specs"
    paths: list[Path] = []
    for spec_path in sorted(directory.glob("*.yaml")):
        spec = load_strategy_spec(spec_path)
        if spec.get("engine_target") == "freqtrade":
            paths.append(convert_spec_file(spec_path))
    return paths
