# Generated by Trading Research OS from YAML spec: mean_reversion_bollinger_rsi_v1
# Spot-only research strategy. Leverage and futures are disabled by design.
from __future__ import annotations

from functools import reduce

import numpy as np
import pandas as pd
from pandas import DataFrame
from freqtrade.strategy import IStrategy


class MeanReversionBollingerRsiV1Strategy(IStrategy):
    """
    Source YAML spec:
    strategy_name: mean_reversion_bollinger_rsi_v1
    asset_class: crypto
    engine_target: freqtrade
    timeframe: 1h
    strategy_type: mean_reversion
    regime_fit:
    - range
    - mean_reversion_candidate
    entry_logic:
      all:
      - indicator: close
        operator: <
        value: bb_lower
      - indicator: rsi_14
        operator: <
        value: 32
      - indicator: spread_proxy
        operator: <
        value: 0.025
    exit_logic:
      any:
      - indicator: close
        operator: '>'
        value: bb_middle
      - indicator: rsi_14
        operator: '>'
        value: 55
    rationale: Attempts to fade stretched moves only when liquidity proxy is acceptable.
    pairs:
    - BTC/USDT
    - ETH/USDT
    - SOL/USDT
    risk:
      stop_loss: -0.03
      take_profit: 0.06
      trailing_stop: true
      max_open_trades: 3
      max_pair_exposure: 0.25
      leverage_allowed: false
      futures_allowed: false
    validation:
      min_trades: 50
      max_drawdown_limit: 0.2
      require_out_of_sample: true
      require_fee_model: true
      require_slippage_model: true
    rejection_criteria:
    - Reject if fee/slippage-adjusted performance is negative.
    - Reject if result is concentrated in one pair or one extreme regime.
    - Reject if out-of-sample performance fails configured thresholds.
    """

    timeframe = "1h"
    can_short = False
    stoploss = -0.03
    trailing_stop = True
    minimal_roi = {'0': 0.06}
    process_only_new_candles = True
    startup_candle_count = 240
    max_open_trades = 3

    def leverage(self, *args, **kwargs) -> float:
        return 1.0

    @staticmethod
    def _rsi(series: pd.Series, window: int = 14) -> pd.Series:
        delta = series.diff()
        gain = delta.clip(lower=0).rolling(window).mean()
        loss = (-delta.clip(upper=0)).rolling(window).mean()
        rs = gain / loss.replace(0, np.nan)
        return 100 - (100 / (1 + rs))

    @staticmethod
    def _atr(dataframe: DataFrame, window: int = 14) -> pd.Series:
        previous_close = dataframe["close"].shift(1)
        true_range = pd.concat(
            [
                dataframe["high"] - dataframe["low"],
                (dataframe["high"] - previous_close).abs(),
                (dataframe["low"] - previous_close).abs(),
            ],
            axis=1,
        ).max(axis=1)
        return true_range.rolling(window).mean()

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe["ema_20"] = dataframe["close"].ewm(span=20, adjust=False).mean()
        dataframe["ema_50"] = dataframe["close"].ewm(span=50, adjust=False).mean()
        dataframe["ema_200"] = dataframe["close"].ewm(span=200, adjust=False).mean()
        dataframe["sma_20"] = dataframe["close"].rolling(20).mean()
        dataframe["rsi_14"] = self._rsi(dataframe["close"], 14)
        dataframe["atr_14"] = self._atr(dataframe, 14)
        dataframe["bb_middle"] = dataframe["close"].rolling(20).mean()
        bb_std = dataframe["close"].rolling(20).std()
        dataframe["bb_upper"] = dataframe["bb_middle"] + 2 * bb_std
        dataframe["bb_lower"] = dataframe["bb_middle"] - 2 * bb_std
        fast = dataframe["close"].ewm(span=12, adjust=False).mean()
        slow = dataframe["close"].ewm(span=26, adjust=False).mean()
        dataframe["macd"] = fast - slow
        dataframe["macd_signal"] = dataframe["macd"].ewm(span=9, adjust=False).mean()
        dataframe["macd_hist"] = dataframe["macd"] - dataframe["macd_signal"]
        dataframe["rolling_return_24"] = dataframe["close"].pct_change(24)
        dataframe["rolling_volatility_24"] = dataframe["close"].pct_change().rolling(24).std()
        dataframe["volume_sma_20"] = dataframe["volume"].rolling(20).mean()
        volume_std = dataframe["volume"].rolling(20).std().replace(0, np.nan)
        dataframe["volume_zscore"] = (dataframe["volume"] - dataframe["volume_sma_20"]) / volume_std
        dataframe["drawdown"] = dataframe["close"] / dataframe["close"].cummax() - 1
        dataframe["liquidity_proxy"] = dataframe["close"] * dataframe["volume"]
        dataframe["spread_proxy"] = (dataframe["high"] - dataframe["low"]) / dataframe["close"]
        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        conditions = [(dataframe['close'] < dataframe['bb_lower']) & (dataframe['rsi_14'] < 32) & (dataframe['spread_proxy'] < 0.025)]
        if conditions:
            dataframe.loc[reduce(lambda left, right: left & right, conditions), "enter_long"] = 1
        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        conditions = [(dataframe['close'] > dataframe['bb_middle']) | (dataframe['rsi_14'] > 55)]
        if conditions:
            dataframe.loc[reduce(lambda left, right: left & right, conditions), "exit_long"] = 1
        return dataframe
