from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from core.database import new_id, utc_now
from core.paths import DATA_DIR, resolve_project_path


def create_lean_research_project(
    strategy_name: str,
    symbols: list[str],
    output_dir: str | Path | None = None,
    cash: float = 100000,
    benchmark: str = "SPY",
    data_manifest_path: str | None = None,
) -> dict[str, Any]:
    """Create a local research-only LEAN-style project skeleton."""
    run_id = new_id("lean")
    safe_name = _safe_name(strategy_name)
    root = resolve_project_path(output_dir or (DATA_DIR / "generated" / "lean" / "projects"))
    project_dir = root / f"{safe_name}_{run_id}"
    project_dir.mkdir(parents=True, exist_ok=True)
    config = {
        "strategy_name": strategy_name,
        "symbols": symbols,
        "cash": cash,
        "benchmark": benchmark,
        "mode": "research_only",
        "allow_live_trading": False,
        "allow_brokerage_credentials": False,
        "allow_quantconnect_cloud": False,
        "allow_real_orders": False,
        "allow_futures": False,
        "allow_leverage": False,
        "created_at": utc_now(),
    }
    (project_dir / "strategy_config.json").write_text(json.dumps(config, indent=2), encoding="utf-8")
    (project_dir / "config.json").write_text(
        json.dumps(
            {
                "algorithm-language": "Python",
                "parameters": {},
                "description": "Research-only local LEAN project generated by Trading Research OS.",
                "local-id": int(run_id.split("_")[-1][:8], 16) % 900000000 + 100000000,
            },
            indent=2,
        ),
        encoding="utf-8",
    )
    (project_dir / "lean.json").write_text(
        json.dumps(
            {
                "data-folder": "../../../data/generated/lean/data",
                "organization-id": "00000000000000000000000000000000",
                "job-organization-id": "00000000000000000000000000000000",
                "environment": "backtesting",
                "messaging-handler": "QuantConnect.Messaging.Messaging",
                "job-queue-handler": "QuantConnect.Queues.JobQueue",
                "api-handler": "QuantConnect.Api.Api",
                "map-file-provider": "QuantConnect.Data.Auxiliary.LocalDiskMapFileProvider",
                "factor-file-provider": "QuantConnect.Data.Auxiliary.LocalDiskFactorFileProvider",
                "data-provider": "QuantConnect.Lean.Engine.DataFeeds.DefaultDataProvider",
                "object-store": "QuantConnect.Lean.Engine.Storage.LocalObjectStore",
                "data-permission-manager": "QuantConnect.Data.DataPermissions.DataPermissionManager",
                "live-mode": False,
            },
            indent=2,
        ),
        encoding="utf-8",
    )
    (project_dir / "local_data_manifest.json").write_text(
        json.dumps({"data_manifest_path": data_manifest_path, "label": "LEAN research bridge data"}, indent=2),
        encoding="utf-8",
    )
    (project_dir / "README.md").write_text(_readme(strategy_name, symbols), encoding="utf-8")
    (project_dir / "Main.py").write_text(_algorithm_py(strategy_name, symbols, cash, benchmark), encoding="utf-8")
    return {
        "run_id": run_id,
        "project_path": str(project_dir),
        "strategy_config_path": str(project_dir / "strategy_config.json"),
        "algorithm_path": str(project_dir / "Main.py"),
    }


def build_lean_project(name: str) -> Path:
    """Backward-compatible wrapper for older callers."""
    return Path(create_lean_research_project(name, [])["project_path"])


def _safe_name(value: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_]+", "_", value.strip())
    return cleaned.strip("_").lower() or "lean_research"


def _readme(strategy_name: str, symbols: list[str]) -> str:
    return f"""# {strategy_name}

Research-only LEAN-style project skeleton.

Symbols: {", ".join(symbols) if symbols else "none"}

Safety:
- No live trading.
- No brokerage credentials.
- No QuantConnect cloud login.
- No futures.
- No leverage.
- No real orders.

This skeleton is generated for local research/backtest experiments only. If LEAN CLI is unavailable, this folder is still useful as a reproducible strategy artifact.
"""


def _algorithm_py(strategy_name: str, symbols: list[str], cash: float, benchmark: str) -> str:
    symbol_lines = "\n".join([f'        self.symbols.append(self.AddEquity("{symbol}", Resolution.Daily).Symbol)' for symbol in symbols])
    allocation = "1 / len(self.symbols)" if symbols else "0"
    return f'''"""Research-only LEAN-style algorithm skeleton.

Generated by Trading Research OS. This file is intended for local backtesting only.
It does not configure brokerage credentials, live trading, futures, leverage, or real-order execution.
"""

from AlgorithmImports import *


class { _class_name(strategy_name) }(QCAlgorithm):
    def Initialize(self):
        self.SetStartDate(2022, 1, 1)
        self.SetCash({float(cash)})
        self.symbols = []
{symbol_lines if symbol_lines else "        # Add research symbols here when running with LEAN CLI."}
        self.SetBenchmark("{benchmark}")
        self.rebalanced_month = None

    def OnData(self, data):
        if not self.symbols:
            return
        if self.rebalanced_month == self.Time.month:
            return
        self.rebalanced_month = self.Time.month
        weight = {allocation}
        for symbol in self.symbols:
            if data.ContainsKey(symbol):
                self.SetHoldings(symbol, weight)
'''


def _class_name(strategy_name: str) -> str:
    parts = re.findall(r"[A-Za-z0-9]+", strategy_name)
    name = "".join(part[:1].upper() + part[1:] for part in parts) or "LeanResearchAlgorithm"
    return name if name[0].isalpha() else f"Lean{name}"
